server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://120.78.136.84:3306/school?useSSL=false&characterEncoding=utf8
    username: school
    password: ABCabc-123
    driver-class-name: com.mysql.jdbc.Driver

devtools:
  restart:
    enabled: true
#    是否支持热部署

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.kongww.managementservice.pojo
# 注意：对应实体类的路径

#pagehelper 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql